[package]
name = "rtnw-rs"
version = "0.1.1"
authors = ["blackspotbear <blackspotbear@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
image = "0.22.3"
rand = "0.7.2"
cgmath = "0.17.0"
pbr = "1.0.2"
